CREATE TABLE IF NOT EXISTS schedule.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    name varchar(255) NOT NULL,
    color varchar(7) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT categories_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT categories_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT categories_color_hex CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS categories_user_name_active_uidx
    ON schedule.categories (user_id, name)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS categories_user_active_idx
    ON schedule.categories (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS schedule.schedules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    title varchar(255) NOT NULL,
    location varchar(255) NULL,
    detail text NULL,
    kind varchar(16) NOT NULL,
    granularity varchar(16) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    start_time time NULL,
    end_time time NULL,
    is_completed boolean NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    needs_notification boolean NOT NULL DEFAULT false,
    CONSTRAINT schedules_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT schedules_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES schedule.categories (id) ON DELETE RESTRICT,
    CONSTRAINT schedules_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT schedules_kind_check CHECK (kind IN ('event', 'todo')),
    CONSTRAINT schedules_granularity_check CHECK (granularity IN ('day', 'time')),
    CONSTRAINT schedules_granularity_times CHECK (
        (granularity = 'day' AND start_time IS NULL AND end_time IS NULL)
        OR (granularity = 'time' AND start_time IS NOT NULL AND end_time IS NOT NULL)
    ),
    CONSTRAINT schedules_kind_completed CHECK (
        (kind = 'event' AND is_completed IS NULL)
        OR (kind = 'todo' AND is_completed IS NOT NULL)
    ),
    CONSTRAINT schedules_range CHECK (
        end_date > start_date
        OR (
            end_date = start_date
            AND (granularity = 'day' OR end_time >= start_time)
        )
    )
);

CREATE INDEX IF NOT EXISTS schedules_user_range_active_idx
    ON schedule.schedules (user_id, start_date, end_date)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS schedules_user_category_active_idx
    ON schedule.schedules (user_id, category_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS schedule.preferences (
    user_id integer PRIMARY KEY,
    week_starts_on varchar(16) NOT NULL DEFAULT 'sunday',
    show_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT preferences_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT preferences_week_starts_on_check
        CHECK (week_starts_on IN ('sunday', 'monday'))
);

CREATE TABLE IF NOT EXISTS schedule.hidden_categories (
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT hidden_categories_pkey PRIMARY KEY (user_id, category_id),
    CONSTRAINT hidden_categories_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT hidden_categories_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES schedule.categories (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS hidden_categories_user_idx
    ON schedule.hidden_categories (user_id);

CREATE TABLE IF NOT EXISTS schedule.user_holidays (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    holiday_date date NOT NULL,
    name varchar(255) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT user_holidays_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT user_holidays_name_not_empty CHECK (char_length(name) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_holidays_user_date_active_uidx
    ON schedule.user_holidays (user_id, holiday_date)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS user_holidays_user_date_active_idx
    ON schedule.user_holidays (user_id, holiday_date)
    WHERE is_deleted = false;
