CREATE TABLE IF NOT EXISTS schedule.routines (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    title varchar(255) NOT NULL,
    detail text NULL,
    kind varchar(16) NOT NULL,
    occurrence_type varchar(16) NOT NULL,
    date_rule varchar(16) NULL,
    day_of_month smallint NULL,
    weekday_rule varchar(16) NULL,
    weekday_n smallint NULL,
    weekday varchar(16) NULL,
    adjust_excluded boolean NOT NULL DEFAULT false,
    shift_direction varchar(16) NULL,
    needs_notification boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT routines_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT routines_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES schedule.categories (id) ON DELETE RESTRICT,
    CONSTRAINT routines_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT routines_kind_check CHECK (kind IN ('event', 'todo')),
    CONSTRAINT routines_occurrence_type_check CHECK (occurrence_type IN ('date', 'weekday')),
    CONSTRAINT routines_date_fields_check CHECK (
        (
            occurrence_type = 'date'
            AND date_rule IN ('last_day', 'day_of_month')
            AND weekday_rule IS NULL
            AND weekday_n IS NULL
            AND weekday IS NULL
            AND (
                (date_rule = 'last_day' AND day_of_month IS NULL)
                OR (date_rule = 'day_of_month' AND day_of_month BETWEEN 1 AND 31)
            )
        )
        OR (
            occurrence_type = 'weekday'
            AND weekday_rule IN ('nth', 'nth_from_last')
            AND weekday_n BETWEEN 1 AND 5
            AND weekday IN (
                'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'
            )
            AND date_rule IS NULL
            AND day_of_month IS NULL
        )
    ),
    CONSTRAINT routines_shift_check CHECK (
        (adjust_excluded = false AND shift_direction IS NULL)
        OR (adjust_excluded = true AND shift_direction IN ('earlier', 'later'))
    )
);

CREATE INDEX IF NOT EXISTS routines_user_active_idx
    ON schedule.routines (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS schedule.routine_months (
    routine_id integer NOT NULL,
    month smallint NOT NULL,
    CONSTRAINT routine_months_pkey PRIMARY KEY (routine_id, month),
    CONSTRAINT routine_months_routine_id_fkey
        FOREIGN KEY (routine_id) REFERENCES schedule.routines (id) ON DELETE RESTRICT,
    CONSTRAINT routine_months_month_check CHECK (month BETWEEN 1 AND 12)
);

CREATE INDEX IF NOT EXISTS routine_months_routine_idx
    ON schedule.routine_months (routine_id);

CREATE TABLE IF NOT EXISTS schedule.routine_exclusions (
    routine_id integer NOT NULL,
    exclusion_kind varchar(16) NOT NULL,
    CONSTRAINT routine_exclusions_pkey PRIMARY KEY (routine_id, exclusion_kind),
    CONSTRAINT routine_exclusions_routine_id_fkey
        FOREIGN KEY (routine_id) REFERENCES schedule.routines (id) ON DELETE RESTRICT,
    CONSTRAINT routine_exclusions_kind_check CHECK (
        exclusion_kind IN (
            'holiday', 'sunday', 'monday', 'tuesday', 'wednesday',
            'thursday', 'friday', 'saturday'
        )
    )
);

CREATE INDEX IF NOT EXISTS routine_exclusions_routine_idx
    ON schedule.routine_exclusions (routine_id);

ALTER TABLE schedule.schedules
    ADD COLUMN IF NOT EXISTS routine_id integer NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'schedules_routine_id_fkey'
    ) THEN
        ALTER TABLE schedule.schedules
            ADD CONSTRAINT schedules_routine_id_fkey
            FOREIGN KEY (routine_id) REFERENCES schedule.routines (id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS schedules_user_routine_date_active_idx
    ON schedule.schedules (user_id, routine_id, start_date)
    WHERE is_deleted = false AND routine_id IS NOT NULL;
