-- public 共通テーブル（portal が作成する）

CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id uuid PRIMARY KEY,
    user_id integer NOT NULL,
    expires_at timestamptz NOT NULL,
    CONSTRAINT sessions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON public.sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON public.sessions (expires_at);

CREATE TABLE IF NOT EXISTS public.system_settings (
    key varchar(64) PRIMARY KEY,
    value_text text NULL,
    value_bytes bytea NULL,
    value_media_type varchar(64) NULL,
    CONSTRAINT system_settings_value_xor CHECK (
        (value_text IS NOT NULL AND value_bytes IS NULL)
        OR (value_text IS NULL AND value_bytes IS NOT NULL)
    ),
    CONSTRAINT system_settings_media_type CHECK (
        (value_bytes IS NOT NULL AND value_media_type IS NOT NULL)
        OR (value_text IS NOT NULL AND value_media_type IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.features (
    id varchar(64) PRIMARY KEY,
    title varchar(255) NOT NULL,
    url varchar(2048) NOT NULL,
    icon bytea NOT NULL,
    icon_media_type varchar(64) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.menu_assignments (
    user_id integer NOT NULL,
    feature_id varchar(64) NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT menu_assignments_pkey PRIMARY KEY (user_id, feature_id),
    CONSTRAINT menu_assignments_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT menu_assignments_feature_id_fkey
        FOREIGN KEY (feature_id) REFERENCES public.features (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS menu_assignments_user_order_idx
    ON public.menu_assignments (user_id, display_order);

-- 1x1 PNG
INSERT INTO public.system_settings (key, value_text, value_bytes, value_media_type)
VALUES
    ('login_url', 'http://localhost:5173/portal/login', NULL, NULL),
    ('menu_url', 'http://localhost:5173/portal/menu', NULL, NULL),
    (
        'icon_system',
        NULL,
        decode('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a49444154789c63000100000500010d0a2db40000000049454e44ae426082', 'hex'),
        'image/png'
    ),
    (
        'icon_settings',
        NULL,
        decode('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a49444154789c63000100000500010d0a2db40000000049454e44ae426082', 'hex'),
        'image/png'
    ),
    (
        'icon_back',
        NULL,
        decode('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a49444154789c63000100000500010d0a2db40000000049454e44ae426082', 'hex'),
        'image/png'
    )
ON CONFLICT (key) DO NOTHING;
